### ISSUE TITLE
Front

### ISSUE THREAD

**Issue by HardintTech** [arthur2klein/ProjetSuggestionFilms#6]
- CGU
- Contacts
- Présentation du site
- Création compte / Auth (OAuth?)
- Recherche de films.

- Accès à des pages de présentation de film.

- Labellisation de films (Vu / Non Vu).

- Gestion de la préférence utilisateur (Genres de films préférés, langue de
l’utilisateur).

- Gestion de groupes entre utilisateurs (CRUD).

- Génération de la recommandation pour un groupe donné.

- User Management

Communique seulement avec fastAPI

**Comment by arthur2klein** [comment]
Done
